version: '3.3'
services:
        web:
                build:
                        context: ./php
                        dockerfile: Dockerfile
                image: php:7.4-apache
                container_name: php73
                depends_on:
                        - db
                volumes:
                        - ./php:/var/www/html/
                ports:
                  - 8000:80          
        db:
                build:
                    context: ./mysql
                    dockerfile: Dockerfile
                container_name: database
                volumes:
                        - ./database:/var/run/mysql
                        - ./database/bin:/usr/sbin/mysql
                        - ./database/databases:/var/lib/mysql
                        - ./database/conf:/etc/mysql/conf.d
                image: mysql:5.7
                command: --default-authentication-plugin=mysql_native_password
                restart: always
                environment:
                       MYSQL_ROOT_PASSWORD: 12345678
                       MYSQL_DATABASE: test_db
                       MYSQL_USER: checker
                       MYSQL_PASSWORD: 12345678
                ports:
                        - 127.0.0.1:6033:3306


        phpmyadmin:
                image: phpmyadmin/phpmyadmin
                container_name: pma
                links:
                - db
                environment:
                        PMA_HOST: db
                        PMA_PORT: 3306
                        PMA_ARBITRARY: 1
                ports:
                - 8081:80
                restart: always
                volumes:
                        - ./phpmyadmin:/etc/phpmyadmin/config.user.inc.php
